"use client";

import * as React from "react";
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
} from "@/components/ui/drawer";

const TABS = ["Actions", "Provider", "CLI config"] as const;
type Tab = (typeof TABS)[number];

const CODE: Record<Tab, string> = {
  Actions: `// Each function is a tool the agent can call.
// Return a value and the agent sees it as the tool result.
const actions = {
  pauseCampaign({ id }) {
    setCampaigns(prev =>
      prev.map(c => c.id === id ? { ...c, status: "paused" } : c)
    );
    return { ok: true };
  },

  createCampaign({ name }) {
    const campaign = { id: generateId(), name, status: "draft" };
    setCampaigns(prev => [...prev, campaign]);
    return { ok: true, campaign };
  },

  searchInfluencers({ country, niche }) {
    const results = influencers.filter(i =>
      i.country === country && i.niche.includes(niche)
    );
    return { influencers: results };
  },

  // The agent can navigate your UI too
  switchTab({ tab }) {
    setActiveTab(tab);
    return { ok: true };
  },
};`,

  Provider: `import { BetterAgentProvider } from "@betteragent/react";
import { ChatSidebar } from "@/components/chat/sidebar";

export default function App() {
  const [campaigns, setCampaigns] = useState([]);

  return (
    <BetterAgentProvider
      clientKey={process.env.NEXT_PUBLIC_BETTERAGENT_CLIENT_KEY}
      endUserId={currentUser.id}
      actions={{ pauseCampaign, createCampaign, ... }}
    >
      <YourApp campaigns={campaigns} />
      <ChatSidebar title="Lumen agent" />
    </BetterAgentProvider>
  );
}`,

  "CLI config": `// actions.betteragent.ts
// Generated by: betteragent discover
// Push to backend: betteragent sync
import { z } from "zod";
import { defineAction } from "@betteragent/next";

export const searchCampaigns = defineAction({
  name: "searchCampaigns",
  description: "Search and filter campaigns by name or status.",
  schema: z.object({
    query: z.string().optional(),
    status: z.enum(["live", "paused", "draft"]).optional(),
  }),
});

export const pauseCampaign = defineAction({
  name: "pauseCampaign",
  description: "Pause a live campaign by ID.",
  schema: z.object({ id: z.string() }),
});

export const resumeCampaign = defineAction({
  name: "resumeCampaign",
  description: "Resume a paused campaign.",
  schema: z.object({ id: z.string() }),
});

export const createCampaign = defineAction({
  name: "createCampaign",
  description: "Create a new draft campaign.",
  schema: z.object({ name: z.string().min(1) }),
});

export const updateCampaignBudget = defineAction({
  name: "updateCampaignBudget",
  description: "Set the budget for a campaign in USD.",
  schema: z.object({
    id: z.string(),
    budget: z.number().positive(),
  }),
});

export const bulkPause = defineAction({
  name: "bulkPause",
  description: "Pause multiple live campaigns at once.",
  schema: z.object({ ids: z.array(z.string()) }),
});

export const searchInfluencers = defineAction({
  name: "searchInfluencers",
  description:
    "Find influencers by platform, country, niche, or follower count.",
  schema: z.object({
    query: z.string().optional(),
    platform: z.enum(["instagram", "tiktok", "youtube"]).optional(),
    country: z.string().optional(),
    minFollowers: z.number().optional(),
    niche: z.string().optional(),
  }),
});

export const assignInfluencerToCampaign = defineAction({
  name: "assignInfluencerToCampaign",
  description: "Assign an influencer to a campaign.",
  schema: z.object({
    influencerId: z.string(),
    campaignId: z.string(),
  }),
});

export const getAnalytics = defineAction({
  name: "getAnalytics",
  description: "Get daily analytics for the last N days.",
  schema: z.object({
    campaignId: z.string().optional(),
    days: z.number().int().min(1).max(30).optional(),
  }),
});

export const switchTab = defineAction({
  name: "switchTab",
  description: "Navigate to a different tab in the Lumen UI.",
  schema: z.object({
    tab: z.enum(["campaigns", "influencers", "analytics"]),
  }),
});

export const actions = [
  searchCampaigns, pauseCampaign, resumeCampaign,
  createCampaign, updateCampaignBudget, bulkPause,
  searchInfluencers, assignInfluencerToCampaign,
  getAnalytics, switchTab,
];`,
};

export function CodePanel({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const [tab, setTab] = React.useState<Tab>("Actions");
  const [copied, setCopied] = React.useState(false);

  function copy() {
    navigator.clipboard.writeText(CODE[tab]);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <Drawer open={open} onOpenChange={(v) => !v && onClose()} direction="right">
      <DrawerContent className="sm:max-w-[540px] flex flex-col">
        <DrawerHeader className="border-b border-border pb-3 shrink-0">
          <DrawerTitle className="font-mono text-sm">How it works</DrawerTitle>
          <div className="flex items-center gap-1 mt-2">
            {TABS.map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`font-mono text-[11px] px-2.5 py-1 border transition-colors ${
                  tab === t
                    ? "border-foreground bg-foreground text-background"
                    : "border-border text-muted-foreground hover:border-foreground/40"
                }`}
              >
                {t}
              </button>
            ))}
            <button
              onClick={copy}
              className="ml-auto font-mono text-[11px] px-2.5 py-1 border border-border text-muted-foreground hover:border-foreground/40 transition-colors"
            >
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
        </DrawerHeader>
        <div className="flex-1 overflow-auto bg-zinc-950">
          <pre className="m-0 font-mono text-xs leading-[1.7] text-zinc-100 bg-zinc-950 p-4 min-h-full">
            {CODE[tab]}
          </pre>
        </div>
      </DrawerContent>
    </Drawer>
  );
}
